### ISSUE TITLE
Setting environment variables to falsy values (0, empty string, etc) reverts to default value

### ISSUE THREAD

**Issue by mstyles** [YOURLS/docker#131] opened 2021-12-08 22:05 UTC
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

Due to the way in which environment variables are read within the `user/config.php` file ([here](https://github.com/YOURLS/docker/blob/3abc9454fe88dd74a1512c5899276c5a01bb46a5/config-docker.php#L13)), any environment variables which are set to falsey values will cause the value to be overwritten by the default value.

One area where this has known to cause a problem is with the `YOURLS_DB_PREFIX` variable, since it makes it impossible to set the prefix to an empty string (i.e. no prefix).

### Expectation

Environment variables should support falsy values.

### Reproduction steps

1. Spin up a new yourls instance. e.g.
```
docker run --name some-yourls --link some-mysql:mysql \
    -e YOURLS_SITE="http://localhost:8080" \
    -e YOURLS_USER="example_username" \
    -e YOURLS_PASS="example_password" \
    -e YOURLS_DB_PREFIX="" \
    -d yourls
```
2. Perform yourls installation.
3. Check the yourls database, observe that the tables are all prefixed with "yourls_", despite passing an empty string for YOURLS_DB_PREFIX

**Comment by LeoColomb** [comment] 2021-12-08 22:25
Thanks for opening this case @mstyles.
The thing is that your report is half true, and this is where it becomes a bit tricky: [`getenv` always return a string](https://www.php.net/manual/function.getenv.php), so all "falsy" variables are evaluated as true, with the only exception of an empty string.
That said, it can be improved, I'm open for a pull request.

---
Mostly a duplicate of https://github.com/YOURLS/docker/issues/45

**Closed** 2021-12-08 23:25 UTC
Labels: bug
